"""Generate docs/USAGE.md from the MCP tool schemas and the CLI parser.

Run it after changing a tool signature. CI regenerates it and fails if the committed file drifts.
"""

import argparse
import asyncio
import difflib
import sys
from pathlib import Path

if str(Path(__file__).resolve().parents[1]) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from mcp import Client

from jev_ra import __version__
from jev_ra.cli import build_parser
from jev_ra.mcp_server import build_server

USAGE = Path(__file__).resolve().parents[1] / "docs" / "USAGE.md"
# argparse asks the terminal how wide it is, so the same parser renders differently on a machine
# whose COLUMNS says 40 and one that says nothing at all - and a generated file that depends on
# the shell it was generated in cannot be checked in CI. Fix the width here instead. 78 is what
# an 80-column terminal used to hand it, so the committed file does not churn.
HELP_WIDTH = 78
HEADER = """# Usage

Generated by `scripts/gen_usage.py` from the MCP tool schemas and the CLI parser. Do not edit by
hand; run the script instead.

"""


async def tools():
    async with Client(build_server()) as client:
        listing = await client.list_tools()
    return sorted(listing.tools, key=lambda tool: tool.name)


def render_type(schema):
    if "anyOf" in schema:
        return " | ".join(render_type(option) for option in schema["anyOf"])
    kind = schema.get("type", "any")
    if kind == "array":
        return f"list[{render_type(schema.get('items', {}))}]"
    if kind == "object":
        values = schema.get("additionalProperties")
        return f"object[{render_type(values)}]" if isinstance(values, dict) else "object"
    return {"integer": "int", "number": "float", "string": "str", "boolean": "bool", "null": "none"}.get(kind, kind)


def render_hints(annotations):
    """The MCP annotation hints as one line, in the order the spec lists them."""
    names = (
        ("read_only_hint", "read-only"),
        ("destructive_hint", "destructive"),
        ("idempotent_hint", "idempotent"),
        ("open_world_hint", "open-world"),
    )
    return (
        "Hints: " + ", ".join(f"{label} {'yes' if getattr(annotations, attr) else 'no'}" for attr, label in names) + "."
    )


def render_tool(tool):
    schema = tool.input_schema or {}
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"### `{tool.name}`", "", (tool.description or "").strip(), ""]
    if tool.annotations is not None:
        lines += [render_hints(tool.annotations), ""]
    if not properties:
        lines += ["Takes no arguments.", ""]
        return lines
    lines += ["| argument | type | required | default |", "|---|---|---|---|"]
    for name, spec in properties.items():
        default = spec.get("default")
        shown = "-" if default is None else f"`{default}`"
        kind = render_type(spec).replace("|", "\\|")
        lines.append(f"| `{name}` | {kind} | {'yes' if name in required else 'no'} | {shown} |")
    lines.append("")
    return lines


def cli_help():
    """The CLI help laid out by this script, so no interpreter's argparse can change it.

    argparse's own formatter moved the help column between CPython patch releases, and a usage
    guide that depends on which 3.12 a machine has is not a guide. The words are the parser's;
    only the columns are ours.
    """
    parser = build_parser()
    commands = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    rows = [(choice.dest, choice.help) for choice in commands._choices_actions]
    options = [(", ".join(a.option_strings), a.help) for a in parser._actions if a.option_strings]
    column = max(len(name) for name, _ in rows + options) + 2
    lines = [
        f"usage: {parser.prog} [-h] [--version] COMMAND ...",
        "",
        parser.description,
        "",
        "positional arguments:",
        "  COMMAND",
    ]
    lines += [f"    {name.ljust(column)}{text}" for name, text in rows]
    lines += ["", "options:"]
    lines += [f"  {name.ljust(column + 2)}{text}" for name, text in options]
    return "\n".join(lines)


def render(tool_list):
    lines = [HEADER.rstrip(), "", f"jev-ra {__version__}", "", "## MCP tools", ""]
    for tool in tool_list:
        lines += render_tool(tool)
    lines += ["## Command line", "", "```", cli_help(), "```", ""]
    return "\n".join(lines).rstrip() + "\n"


def build():
    """The full USAGE.md text for the current tool schemas and CLI."""
    return render(asyncio.run(tools()))


def main(argv=None):
    parser = argparse.ArgumentParser(prog="gen_usage", description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed file is out of date")
    args = parser.parse_args(argv)
    text = build()
    if args.check:
        current = USAGE.read_text() if USAGE.exists() else ""
        if current != text:
            print(f"{USAGE} is out of date; run `uv run python scripts/gen_usage.py`", file=sys.stderr)
            diff = difflib.unified_diff(current.splitlines(), text.splitlines(), "committed", "generated", lineterm="")
            print("\n".join(list(diff)[:80]), file=sys.stderr)
            return 1
        return 0
    USAGE.parent.mkdir(parents=True, exist_ok=True)
    USAGE.write_text(text)
    print(f"wrote {USAGE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
