"""Generate docs/USAGE.md from the MCP tool schemas and the CLI parser.

Run it after changing a tool signature. CI regenerates it and fails if the committed file drifts.
"""

import argparse
import asyncio
import difflib
import sys
from pathlib import Path

if str(Path(__file__).resolve().parents[1]) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from mcp import Client

from jev_ra import __version__
from jev_ra.cli import build_parser
from jev_ra.mcp_server import build_server

USAGE = Path(__file__).resolve().parents[1] / "docs" / "USAGE.md"
# argparse asks the terminal how wide it is, so the same parser renders differently on a machine
# whose COLUMNS says 40 and one that says nothing at all - and a generated file that depends on
# the shell it was generated in cannot be checked in CI. Fix the width here instead. 78 is what
# an 80-column terminal used to hand it, so the committed file does not churn.
HELP_WIDTH = 78
HEADER = """# Usage

Generated by `scripts/gen_usage.py` from the MCP tool schemas and the CLI parser. Do not edit by
hand; run the script instead.

"""


async def tools():
    async with Client(build_server()) as client:
        listing = await client.list_tools()
    return sorted(listing.tools, key=lambda tool: tool.name)


def render_type(schema):
    if "anyOf" in schema:
        return " | ".join(render_type(option) for option in schema["anyOf"])
    kind = schema.get("type", "any")
    if kind == "array":
        return f"list[{render_type(schema.get('items', {}))}]"
    if kind == "object":
        values = schema.get("additionalProperties")
        return f"object[{render_type(values)}]" if isinstance(values, dict) else "object"
    return {"integer": "int", "number": "float", "string": "str", "boolean": "bool", "null": "none"}.get(kind, kind)


def render_tool(tool):
    schema = tool.input_schema or {}
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"### `{tool.name}`", "", (tool.description or "").strip(), ""]
    if not properties:
        lines += ["Takes no arguments.", ""]
        return lines
    lines += ["| argument | type | required | default |", "|---|---|---|---|"]
    for name, spec in properties.items():
        default = spec.get("default")
        shown = "-" if default is None else f"`{default}`"
        kind = render_type(spec).replace("|", "\\|")
        lines.append(f"| `{name}` | {kind} | {'yes' if name in required else 'no'} | {shown} |")
    lines.append("")
    return lines


def cli_help(width=HELP_WIDTH):
    """The CLI help at the width this script fixes, never the one the terminal happens to have."""
    parser = build_parser()
    parser.formatter_class = lambda prog: argparse.HelpFormatter(prog, width=width)
    return parser.format_help().rstrip()


def render(tool_list):
    lines = [HEADER.rstrip(), "", f"jev-ra {__version__}", "", "## MCP tools", ""]
    for tool in tool_list:
        lines += render_tool(tool)
    lines += ["## Command line", "", "```", cli_help(), "```", ""]
    return "\n".join(lines).rstrip() + "\n"


def build():
    """The full USAGE.md text for the current tool schemas and CLI."""
    return render(asyncio.run(tools()))


def main(argv=None):
    parser = argparse.ArgumentParser(prog="gen_usage", description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed file is out of date")
    args = parser.parse_args(argv)
    text = build()
    if args.check:
        current = USAGE.read_text() if USAGE.exists() else ""
        if current != text:
            print(f"{USAGE} is out of date; run `uv run python scripts/gen_usage.py`", file=sys.stderr)
            diff = difflib.unified_diff(current.splitlines(), text.splitlines(), "committed", "generated", lineterm="")
            print("\n".join(list(diff)[:80]), file=sys.stderr)
            return 1
        return 0
    USAGE.parent.mkdir(parents=True, exist_ok=True)
    USAGE.write_text(text)
    print(f"wrote {USAGE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
